# Site settings
title: John Tuttle Comedy
header-img: img/home-bg.png
email: thejwt@gmail.com
copyright_name: elTuttle
description: > # this means to ignore newlines until "baseurl:"
  John Tuttle's Thoughts and Works
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  elTuttle
learn_profile: elTuttle
email_username: thejwt@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
